### ISSUE TITLE
Angular v10 changed how libraries should  deal with tslib

### ISSUE THREAD

**Issue by Splaktar** [ftischler/ngx-rxjs-zone-scheduler#18]
```js
npm WARN ngx-rxjs-zone-scheduler@9.0.0 requires a peer of tslib@^1.10.0 but none is installed. 
You must install peer dependencies yourself.
```
- Angular CLI projects on v10 now list `"tslib": "^2.0.0"` in `dependencies`.
- Angular CLI libraries now list `"tslib": "^2.0.0"` in `dependencies` instead of `peerDependencies`.

**Comment by ftischler** [comment]
Thanks for your PR! :-)
