### ISSUE TITLE
Producing an observable from service outside Angular zone

### ISSUE THREAD

**Issue by rmeshksar** [ftischler/ngx-rxjs-zone-scheduler#38]
Hi,
Thanks for the great library. 
Imagine there is a service that exports an observable and component needs to force that observable to be produced outside Angular zone.

Is this even possible without changing the service?

To simplify the question, here is a method in the serivce:

```
public getStream() {
   return timer(0, 1000);
}
```

This method always triggers change detection. How can this method be consumed in the component with producing outside Angular zone?

Thanks.

**Comment by ftischler** [comment]
Hello, afaik producing outside NgZone is not possible without changing the service. The only option I can think of is to use the observeOn opterator and leave ngZone beforce subscribing in the component like mentioned in the documentation: 

```typescript
public viewStream$: Observable<unknown> = this.someService.getStream().pipe(observeOn(leaveNgZone(this.ngZone)));
``` 

After this you can subscribe the new Observable via .subscribe(), AsyncPipe, etc. 

Does this solve your problem or did you already consider to use this without any success?

**Comment by rmeshksar** [comment]
Hi, Thank you for you response and apologize for delay. I totally missed this.

Your approach did not work but simply putting call to the service in the runOutsideAngularZone works.

 ```javascript
    this.ngZone.runOutsideAngular(() => {
      this.dataService.getStream()
        .subscribe(console.log);
    });
```
