### ISSUE TITLE
Upgrade to angular 17

### ISSUE THREAD

**Issue by elgerm** [ftischler/ngx-rxjs-zone-scheduler#63]
Hi, any chance this repo gets updated to the latest and greatest angular 17? My projects depend on your lib.

Cheers,

Elger

**Comment by ftischler** [comment]
@elgerm @Timebutt Thanks for the issue and your contribution! I was also already working on a update as well but had no time to finish it up. I will merge our work together and release the new version soon.

**Comment by ftischler** [comment]
I just published v17 with support for angular 17 on npm, you should be able to update now
